### ISSUE TITLE
migrating to version 5

### ISSUE THREAD

**Issue by j-faria** [j-faria/kima#79]
I'm planning a new major release with very significant changes and (hopefully) improvements.
This issue will keep track of the progress.

- [ ] merge `v5` into `beta` (probably several times...)  1/?
- [ ] make the move from `src` to `kima` folders consistent
- [ ] "re-implement" all examples
- [ ] add new examples
- [ ] new models
- [ ] new interface between `pykima` and the C++ implementations of GPs and (probably) distributions
- [ ] update documentation
  - [ ] docs for `kima`
  - [ ] docs for `pykima`
  - [ ] update [kima.science](kima.science)
- [ ] ...
- [ ] fix j-faria/issue_transfer#13 
- [ ] fix j-faria/issue_transfer#11 
- [ ] fix j-faria/issue_transfer#12

**Comment by j-faria** [comment]
pybind11 extensions are not working in Python 3.11
